---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: web
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jglotain@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}